### ISSUE TITLE
Probable parsing bug

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs-ds-help#33]
I caught this during debugging:
```go
import (
	"testing"

	ds "github.com/ipfs/go-datastore"
	dshelp "github.com/ipfs/go-ipfs-ds-help"
)

func TestFoo(t *testing.T) {
	key := "/AFKREIDK5CTVKVJAT7LMIQKXYCXNQALOOY77INNBTTYYN53IMMKACQ77OIII"
	key2 := ds.RawKey(key)
	_, err := dshelp.DsKeyToCid(key2)
	if err != nil {
		// Print "panic: trailing bytes in data buffer passed to cid Cast"
		panic(err)
	}
}
```

Not exactly sure what's happening here but that looks like a bug.

**Comment by aschmahmann** [comment]
@MichaelMure it's hard to tell what's actually going on here. Assuming you're using go-ipfs-ds-help v0.1.1 (i.e. what go-ipfs uses) DsKeyToCid assumes the format is `/<base32 encoded CID without the multibase prefix>` .  That text is not a valid CID (i.e. https://cid.ipfs.io/#BAFKREIDK5CTVKVJAT7LMIQKXYCXNQALOOY77INNBTTYYN53IMMKACQ77OIII shows an error). However, if you trip the last two characters off the end it seems valid (i.e. https://cid.ipfs.io/#BAFKREIDK5CTVKVJAT7LMIQKXYCXNQALOOY77INNBTTYYN53IMMKACQ77OI is ok).

If there's a problem it's probably elsewhere (e.g. your datastore or whatever put the data into your datastore).

**Comment by aschmahmann** [comment]
@MichaelMure do you have any context for where this datastore entry came from or how it was produced?

**Comment by MichaelMure** [comment]
Not really. I got the warning message when running some piece of the Infura stack. What's sure is that this block was either stored or corrupted by one of the PL module, or possibly by go-ds-s3. Either way I understand there is not much clue to find what really happened.

**Comment by aschmahmann** [comment]
ok, I'm going to close this as non-actionable for now. If this comes up again or you have any more information feel free to reopen.
